export const WEEK_TOPICS: Record<string, Record<number, string>> = {
  DEVELOPER: {
    1: "The Agent Factory paradigm",
    2: "Agent architecture and memory",
    3: "Context engineering and prompt design",
    4: "MCP — giving agents tools",
    5: "Multi-agent systems",
    6: "Reading and translating specs",
    7: "Persistent state and data handling",
    8: "Error handling, safety, and guardrails",
    9: "Deployment basics",
    10: "Capstone kickoff",
    11: "Build sprint",
    12: "Demo Day",
  },
  PROFESSIONAL: {
    1: "Why AI is non-negotiable",
    2: "The Agent Triangle",
    3: "Markdown specs — writing instructions AI can follow",
    4: "Detecting broken reasoning",
    5: "Workflow mapping",
    6: "Reading code like a manager",
    7: "Scoping agents for Kampala problems",
    8: "Writing the capstone spec",
    9: "The Digital FTE business case",
    10: "Capstone kickoff — own the requirements",
    11: "Test, audit, and file issues",
    12: "Demo Day — presenting the business case",
  },
};
